### PR TITLE
Added postinstall in package.json

### PR DESCRIPTION
**Pull request by lielfr**
This should do the trick

### CODE REVIEW

**Comment by prokopsimek** [comment]
@lielfr I don't think that's correct. It would work if the user installs the DX Scanner globally first but what about the developers of DX Scanner? 
While they run `yarn install` the script `postinstall` will be started and they don't have to have installed the `dx-scanner` cmd globally.

**Comment by prokopsimek** [comment]
@lielfr Thanks! I'll review that tomorrow in the morning (in 9 hours).

**Comment by lielfr** [comment]
The Windows build fails after the post-install script for some reason.

**Pull request merged**
