### PR TITLE
Do not require lockfiles in gitignore practice

### LINKED ISSUE #96: Invalid detection of lock files in a .gitignore practice
There should be fixed the condition in https://github.com/DXHeroes/dx-scanner/blob/019ee6aaf1a9925ff3768a482fc7f8bbbc570082/src/practices/JavaScript/JsGitignoreCorrectlySetPractice.ts#L49. It should work on most of the repositories but at least on https://github.com/github/gitignore/blob/master/Node.gitignore and it should work on DX Scanner.

### PR DESCRIPTION
**Pull request by vlasy**
As mentioned in [npm](https://docs.npmjs.com/files/package-locks#using-locked-packages) and [yarn](https://yarnpkg.com/en/docs/yarn-lock#toc-check-into-source-control) docs, adding lockfile to VCS might be perfectly valid option

Resolves #96

### CODE REVIEW

**Comment by vlasy** [comment]
I changed the code to allow only one lockfile in gitignore - according to requirements

**Comment by prokopsimek** [comment]
@vlasy Wouldn't be better to enforce users have one of the lockfiles in a `.gitignore` file as default? 

I mean when you write an app, it's strongly recommended (best practice) to have one of these lockfiles in `.gitignore` but if the package is a library, you can disable the practice with `.dxscannerrc.yaml` config file in the root of your repository. 

I guess most of JS projects are apps instead of libraries event if it's a library, most developers would prefer to have a lockfile committed?

**Comment by vlasy** [comment]
@prokopsimek You are right, that might be the sensible default and users can turn the rule off. I was too benevolent :)

**Comment by prokopsimek** [comment]
@vlasy Thanks! 💙

**Pull request merged**
