### PR TITLE
Added GitHub support for self-hosted repositories (fix: #269)

### PR DESCRIPTION
**Pull request by haardikdharma10**
## Description

Added support for Github, similar to Gitlab, for self-hosted repositories.

## Motivation and Context
Fixes: #269

### CODE REVIEW

**Comment by adelkahomolova** [comment]
Can you add tests for your code? Thank you :) @haardikdharma10

**Comment by haardikdharma10** [comment]
Sure thing @adelkahomolova, is there an example test template I can refer?

**Comment by adelkahomolova** [comment]
> Sure thing @adelkahomolova, is there an example test template I can refer?

Sure, you can be inspired by three already existing component detectors. For example [JavaScriptComponentDetector](https://github.com/DXHeroes/dx-scanner/blob/master/src/detectors/JavaScript/JavaScriptComponentDetector.spec.ts)

@haardikdharma10

**Comment by adelkahomolova** [comment]
@haardikdharma10 Hi, how are you going? Do you need any help?

**Comment by haardikdharma10** [comment]
Hii @adelkahomolova, yeah I'm having difficulties in adding tests, if you can help me with that? What do you think about the code I pushed? 🤔

**Comment by adelkahomolova** [comment]
The problem is you've just copied the code from implementation for GitLab. I told you this isn't the way you should proceed. The APIs are different. There are no `projects` in GitHub and also the Github client (Octokit) doesn't have methods `this.client.Versin.check()`, `this.client.Projects.list()` nor `this.client.Users.listGroups()`. I also don't think Github has properties like `revision` and `version`. So the reason why you have difficulties with tests is, that your code can't be working since you're using methods that don't exist on the GH Client (octokit). 
Here is the documentation for GitHub REST API where you should find everything you need for completing this task. https://docs.github.com/en/free-pro-team@latest/rest
@haardikdharma10

**Comment by adelkahomolova** [comment]
Hi @haardikdharma10 did you work on the pull request?

**Comment by adelkahomolova** [comment]
Hi, @haardikdharma10 , is there any progress? :)

**Pull request closed without merging**
