### PR TITLE
Fix GH action Dockerfile spec

### PR DESCRIPTION
**Pull request by vlasy**
## Description

Fixes GH action entrypoint script. Add missing git to action Dockerfile. Fix GH action specs 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have added new practice to practice list in README.md.
- [x] I have read the **CONTRIBUTING** document.
- [x] I haven't repeated the code. (DRY)
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by adelkahomolova — APPROVED** [review]

**Review by prokopsimek — CHANGES_REQUESTED** [review]
@vlasy There is a file called `entrypoint.sh` in the root that is empty. Is that possible to delete it?

**Comment by vlasy** [comment]
> @vlasy There is a file called `entrypoint.sh` in the root that is empty. Is that possible to delete it?

The Github shows "empty file" because the only change was the file permissions (making the file executable). The file itself still contains the code: https://github.com/DXHeroes/dx-scanner/blob/3963fb96146e5d081b38f5fbcd752634b3258185/entrypoint.sh

**Review by prokopsimek — APPROVED** [review]
@vlasy Ok, thanks! 👍

**Pull request merged**
