### PR TITLE
Update DeprecatedTSLintPractice.ts

### PR DESCRIPTION
**Pull request by ridlees**
Changed URL to the article in DXKB.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have updated the documentation accordingly.
- [ ] I have added new practice to practice list in README.md.
- [x] I have read the **CONTRIBUTING** document.
- [x] I haven't repeated the code. (DRY)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by Jakub-Vacek — APPROVED** [review]

**Review by ryzzaki — APPROVED** [review]

**Review by adelkahomolova — COMMENTED** [review]
I'm not sure if we should use an article about linting here. It's specifically about deprecated TSLint, the user already uses some linter but the wrong one. The truth is, that we mention ESLint in the article but we not mention why not to use TSLint. But I know that we want to link DX Scanner with our Knowledge Base. So I just want to consider it. What do you think?

**Comment by ridlees** [comment]
Exactly what I was asking Prokop (that there is just a mention). We can theoretically update the article to explain why "TSlint is bad practice". Or we can use the existing article https://developerexperience.io/practices/javascript-front-end-build-tools which mentions ES linter and add a short reasoning why ESlinter is better.

**Comment by adelkahomolova** [comment]
> Exactly what I was asking Prokop (that there is just a mention). We can theoretically update the article to explain why "TSlint is bad practice". Or we can use the existing article [developerexperience.io/practices/javascript-front-end-build-tools](https://developerexperience.io/practices/javascript-front-end-build-tools) which mentions ES linter and add short reasoning why ESlinter is better.

Hmmm, what about just mentioning that TSLint is deprecated in the linting article and put the URL for the article why it is deprecated there? @ridlees

**Comment by ridlees** [comment]
Great Idea, will be done ASAP

**Pull request merged**
