### PR TITLE
Feature/html reporter (#75)

### PR DESCRIPTION
**Pull request by Alexandr22022000**
## Description

Added HTMLReporter

## Types of changes

- [x] New feature HTMLReporter

## Checklist:

- [x] I have updated the documentation accordingly.
- [x] I have added new practice to practice list in README.md.
- [x] I have read the **CONTRIBUTING** document.
- [x] I haven't repeated the code. (DRY)
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by prokopsimek** [comment]
Solves #75

**Comment by Alexandr22022000** [comment]
@prokopsimek I fixed small issues in this pull request

**Comment by adelkahomolova** [comment]
> @prokopsimek I fixed small issues in this pull request

Greate. Can you resolve merge conflicts please? @Alexandr22022000

**Pull request merged**
