### PR TITLE
Custom fixer report

### PR DESCRIPTION
**Pull request by vlasy**
## Description

Add new reporter for showing info about fixes being made during the fix run

Example of fixer output
Screenshot from 2020-03-05 11-06-07

## Motivation and Context

User should have some info about what was fixed during the fix run and how it affected the score.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have added new practice to practice list in README.md.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I haven't repeated the code. (DRY)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by prokopsimek** [comment]
@vlasy The code seems to be fine but the PR CI failed because of an HTTP error.

- [ ] please add a screenshot of `--fix` report
- [ ] fix the HTTP error

**Comment by prokopsimek** [comment]
# [DX Scanner](https://dxscanner.io) Report <a href="https://dxscanner.io" target="_blank">DXScanner.io</a>
## https://github.com/DXHeroes/dx-scanner 

<h3>⚠️ Improvements with medium impact
</h3>
<details>
<summary>Break down large pull requests into smaller ones</summary>

<b>Large pull request are hard to code review and it reduces the probability of finding bugs. Split your PRs into logical units. Do not have PR with more than 1000 changes.</b> <a href="https://medium.com/@hugooodias/the-anatomy-of-a-perfect-pull-request-567382bb6067">https://medium.com/@hugooodias/the-anatomy-of-a-perfect-pull-request-567382bb6067</a>
</details>
<details>
<summary>Solve Issues Continuously</summary>

<b>Do not have an open Issues more than 60 days. Solve Issues continuously.</b> <a href="https://hackernoon.com/45-github-issues-dos-and-donts-dfec9ab4b612">https://hackernoon.com/45-github-issues-dos-and-donts-dfec9ab4b612</a>
</details>
<details>
<summary>Update Dependencies of Minor and Patch Level</summary>

<b>Keep the dependencies updated to eliminate security concerns and compatibility issues. Use, for example, npm-check-updates.</b> <a href="https://dxkb.io/p/updating-the-dependencies">https://dxkb.io/p/updating-the-dependencies</a>


 Name                             | New    | Current  
---------------------------------- | -------- | ----------
 cross-env                        | 7.0.1  | 7.0.0    
 npm-check-updates                | 4.0.3  | 4.0.1    
 tslib                            | 1.11.1 | 1.11.0   
 typescript                       | 3.8.3  | 3.8.2    
 @types/node                      | 13.7.7 | 12.12.28 
 nock                             | 12.0.2 | 12.0.1   
 @types/node                      | 13.7.7 | 12.12.28 
 @typescript-eslint/eslint-plugin | 2.22.0 | 2.21.0   
 @typescript-eslint/parser        | 2.22.0 | 2.21.0   

  <b>Impact changed from high to medium.</b>
</details>
<h3>🔔 Improvements with minor impact
</h3>
<details>
<summary>Write Commit Messages by Convention</summary>

<b></b> <a href="https://www.conventionalcommits.org/">https://www.conventionalcommits.org/</a>


 Commit Message                                                                | Problems                                                           
------------------------------------------------------------------------------- | --------------------------------------------------------------------
 fix: relocated interfaces of individual practices in the current architecture | header must not be longer than 72 characters, current length is 77 

</details>
<details>
<summary>Update Dependencies of Major Level</summary>

<b>Keep the dependencies updated to have all possible features. Use, for example, npm-check-updates.</b> <a href="https://dxkb.io/p/updating-the-dependencies">https://dxkb.io/p/updating-the-dependencies</a>


 Name          | New     | Current  
--------------- | --------- | ----------
 @octokit/rest | ^17.0.0 | ^16.0.0  
 @types/node   | 13.7.7  | 12.12.28 

</details>
<details>
<summary>Use a JS Logging Library</summary>

<b>Use a logging library to avoid errors and even cyber attacks. The most widely used logging library in the JavaScript community is Winston.</b> <a href="https://www.npmjs.com/package/winston/">https://www.npmjs.com/package/winston/</a>
</details>



---



Implementation is not adoption.
We can help you with both. :-)
[dxheroes.io](https://dxheroes.io)



##### Found a bug? Please <a href="https://github.com/DXHeroes/dx-scanner/issues" target="_blank">report</a>.

**Comment by vlasy** [comment]
Added the screenshot. Build succeeds after rebase.

**Pull request merged**
