### PR TITLE
feat(reporters): show error message from failed practice in CLI log

### PR DESCRIPTION
**Pull request by prokopsimek**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have added new practice to practice list in README.md.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I haven't repeated the code. (DRY)
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by prokopsimek** [comment]
# [DX Scanner](https://dxscanner.io) Report <a href="https://dxscanner.io" target="_blank">DXScanner.io</a>
## https://github.com/DXHeroes/dx-scanner 

<h3>⚠️ Improvements with medium impact
</h3>
<details>
<summary>Break down large pull requests into smaller ones</summary>

<b>Large pull request are hard to code review and it reduces the probability of finding bugs. Split your PRs into logical units. Do not have PR with more than 1000 changes.</b> <a href="https://medium.com/@hugooodias/the-anatomy-of-a-perfect-pull-request-567382bb6067">https://medium.com/@hugooodias/the-anatomy-of-a-perfect-pull-request-567382bb6067</a>
</details>
<details>
<summary>Solve Issues Continuously</summary>

<b>Do not have an open Issues more than 60 days. Solve Issues continuously.</b> <a href="https://hackernoon.com/45-github-issues-dos-and-donts-dfec9ab4b612">https://hackernoon.com/45-github-issues-dos-and-donts-dfec9ab4b612</a>
</details>
<details>
<summary>Update Dependencies of Minor and Patch Level</summary>

<b>Keep the dependencies updated to eliminate security concerns and compatibility issues. Use, for example, npm-check-updates.</b> <a href="https://github.com/tjunnone/npm-check-updates">https://github.com/tjunnone/npm-check-updates</a>


 Name                             | New    | Current  
---------------------------------- | -------- | ----------
 commander                        | ^4.1.1 | ^4.1.0   
 @types/node                      | 13.7.0 | 12.12.26 
 @typescript-eslint/eslint-plugin | 2.19.0 | 2.18.0   
 @typescript-eslint/parser        | 2.19.0 | 2.18.0   
 ts-jest                          | 25.2.0 | 25.1.0   

  <b>Impact changed from high to medium.</b>
</details>
<details>
<summary>ESLint Without Errors</summary>

<b>Use the ESLint correctly. You have some errors.</b> <a href="https://eslint.org/">https://eslint.org/</a>
</details>
<h3>🔔 Improvements with minor impact
</h3>
<details>
<summary>Write Commit Messages by Convention</summary>

<b></b> <a href="https://www.conventionalcommits.org/">https://www.conventionalcommits.org/</a>


 Commit Message                             | Problems                                                               
-------------------------------------------- | ------------------------------------------------------------------------
 fix(init): Win architecture & tests (#238) | subject must not be sentence-case, start-case, pascal-case, upper-case 
                                            |                                                                        
 fix(init): Win architecture & tests        |                                                                        
 fix(init): Win architecture & tests        | subject must not be sentence-case, start-case, pascal-case, upper-case 

</details>
<details>
<summary>Update Dependencies of Major Level</summary>

<b>Keep the dependencies updated to have all possible features. Use, for example, npm-check-updates.</b> <a href="https://github.com/tjunnone/npm-check-updates">https://github.com/tjunnone/npm-check-updates</a>


 Name                        | New    | Current  
----------------------------- | -------- | ----------
 bitbucket                   | 2.0.0  | 1.17.1   
 @semantic-release/changelog | 5.0.0  | 3.0.6    
 @semantic-release/git       | 9.0.0  | 8.0.0    
 @types/node                 | 13.7.0 | 12.12.26 
 semantic-release            | 17.0.2 | 16.0.4   

</details>
<details>
<summary>Use a JS Logging Library</summary>

<b>Use a logging library to avoid errors and even cyber attacks. The most widely used logging library in the JavaScript community is Winston.</b> <a href="https://www.npmjs.com/package/winston/">https://www.npmjs.com/package/winston/</a>
</details>


---



Implementation is not adoption.
We can help you with both. :-)
[dxheroes.io](https://dxheroes.io)



##### Found a bug? Please <a href="https://github.com/DXHeroes/dx-scanner/issues" target="_blank">report</a>.

**Comment by prokopsimek** [comment]
@ryzzaki will continue in this task for non-blocking run of DX Scanner.

**Comment by ryzzaki** [comment]
@prokopsimek Please review my latest commit with the proposed changes on how DXS could operate if the user is disconnected from the internet. 

I am trying to force DXS to perform the scan regardless whether the user is connected or disconnected from the internet, but has linked a remote repo in his local git. One big obstacle was to distinguish between the 2 states: Online or Offline => this is done so that DXS would not ask the user to enter the Personal Token if he/she is disconnected.

Let me know if you agree with the proposed changes in the business logic and whether I should continue with this implementation or revert the commit and try to find a different way of implementing the non-blocking-scanner features. I was able to get this to work by disconnecting my laptop from the network and running DXS with active changes on a local NestJS project repo, however, some tests are failing (as expected).

**Comment by prokopsimek** [comment]
> @prokopsimek Please review my latest commit with the proposed changes on how DXS could operate if the user is disconnected from the internet.
> 
> I am trying to force DXS to perform the scan regardless of whether the user is connected or disconnected from the internet, but has linked a remote repo in his local git. One big obstacle was to distinguish between the 2 states: Online or Offline => this is done so that DXS would not ask the user to enter the Personal Token if he/she is disconnected.
> 
> Let me know if you agree with the proposed changes in the business logic and whether I should continue with this implementation or revert the commit and try to find a different way of implementing the non-blocking-scanner features. I was able to get this to work by disconnecting my laptop from the network and running DXS with active changes on a local NestJS project repo, however, some tests are failing (as expected). Let's continue. :) 

I guess there are 2 ways of implementation. Yours is the first one, and the second could be to catch all 500 errors somehow. I am not sure what is a better way. I like your idea, for now, more than the second because now we can just run the DX Scanner, and we don't have additional work with error handling.

**Comment by ryzzaki** [comment]
I attempted to try-catch LanguageIndependent practices that involve remote repositories (i.e. fetching commits and pull requests) - and I came to a conclusion that there are too many things to catch at the moment as @prokopsimek mentioned before and the solution became overly complicated. I ended up writing tests only for `ScanningStrategyDetector.spec.ts` as other practices absolutely require Net Connect.

**Comment by prokopsimek** [comment]
@ryzzaki Approved ✅ You can merge it.

**Pull request merged**
